# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_seats',
            field=models.CharField(default='', max_length=2),
        ),
    ]
