# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='username',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
