# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 10:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableWeekDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday$')])),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_rsv.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='RelevantAirports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_rsv.Airport')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_rsv.Passenger')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight_class',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(regex='^Booked|Waiting$')]),
        ),
    ]
