# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0002_ticket_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='description',
        ),
        migrations.AddField(
            model_name='offers',
            name='discount',
            field=models.CharField(default='', max_length=2),
        ),
    ]
