# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 21:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0003_auto_20180322_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableweekdays',
            name='week_day',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday', regex='^Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday$')]),
        ),
    ]
