# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 14:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0003_passenger_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='type',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='type',
        ),
        migrations.AddField(
            model_name='airline',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
