# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0004_auto_20180326_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='destination_id',
            field=models.ForeignKey(default=10000, on_delete=django.db.models.deletion.CASCADE, related_name='destination_id', to='air_rsv.Airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='source_id',
            field=models.ForeignKey(default=10001, on_delete=django.db.models.deletion.CASCADE, related_name='source_id', to='air_rsv.Airport'),
            preserve_default=False,
        ),
    ]
