# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 15:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0004_auto_20180318_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Flight id must be entered in the format: '100000'. A 5 digit number not starting with 0.", regex='^[1-9]\\d{4,4}$')])),
                ('airport_name', models.CharField(max_length=20)),
                ('airport_country', models.CharField(max_length=20)),
                ('airport_city', models.CharField(max_length=20)),
                ('airport_news', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Flight id must be entered in the format: '1000000000'. A 10 digit number not starting with 0.", regex='^[1-9]\\d{9,9}$')])),
                ('business_classfare', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Valid Price must be entered in the format: '5000.05 or 5000'.", regex='^\\d+(\\.\\d{1,2})?$')])),
                ('economy_classfare', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Valid Price must be entered in the format: '5000.05 or 5000'.", regex='^\\d+(\\.\\d{1,2})?$')])),
                ('total_seats', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Enter valid number of seats', regex='^\\d+$')])),
                ('daysoffset', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(message='Enter valid offset', regex='^\\d$')])),
                ('departure_time', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Enter valid time of format HH:MM 24hour', regex='^[0-2][0-3]:[0-5][0-9]$')])),
                ('arrival_time', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Enter valid time of format HH:MM 24hour', regex='^[0-2][0-3]:[0-5][0-9]$')])),
                ('airline_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_rsv.Airline')),
            ],
        ),
        migrations.CreateModel(
            name='Flight_instance',
            fields=[
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='air_rsv.Airport')),
                ('date_of_departure', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid date', regex='^\\s*(3[01]|[12][0-9]|0?[1-9])\\.(1[012]|0?[1-9])\\.((?:19|20)\\d{2})\\s*$')])),
                ('available_seats', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Enter valid number of seats', regex='^\\d+$')])),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='departureid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationid', to='air_rsv.Airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='sourceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceid', to='air_rsv.Airport'),
        ),
    ]
