# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 10:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0005_auto_20180318_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='air_rsv.Airport')),
                ('startdate', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid date', regex='^\\s*(3[01]|[12][0-9]|0?[1-9])\\.(1[012]|0?[1-9])\\.((?:19|20)\\d{2})\\s*$')])),
                ('end_date', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid date', regex='^\\s*(3[01]|[12][0-9]|0?[1-9])\\.(1[012]|0?[1-9])\\.((?:19|20)\\d{2})\\s*$')])),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
