# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0005_auto_20180326_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevantairports',
            name='airport_id',
        ),
        migrations.RemoveField(
            model_name='relevantairports',
            name='email',
        ),
        migrations.DeleteModel(
            name='RelevantAirports',
        ),
    ]
