# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0006_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
