# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 16:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0007_auto_20180318_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateStop',
            fields=[
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='air_rsv.Flight')),
                ('stop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='air_rsv.Airport')),
                ('daysoffset', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(message='Enter valid offset', regex='^\\d$')])),
                ('departure_time', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Enter valid time of format HH:MM 24hour', regex='^[0-2][0-3]:[0-5][0-9]$')])),
                ('arrival_time', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Enter valid time of format HH:MM 24hour', regex='^[0-2][0-3]:[0-5][0-9]$')])),
            ],
        ),
        migrations.CreateModel(
            name='OfferedBy',
            fields=[
                ('airline_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='air_rsv.Airline')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='air_rsv.Offers')),
            ],
        ),
        migrations.CreateModel(
            name='ValidOffers',
            fields=[
                ('passenger_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='air_rsv.Passenger')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='air_rsv.Offers')),
            ],
        ),
        migrations.AlterField(
            model_name='flight_instance',
            name='date_of_departure',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Enter valid date', regex='^\\s*(3[01]|[12][0-9]|0?[1-9])\\.(1[012]|0?[1-9])\\.((?:19|20)\\d{2})\\s*$')]),
        ),
        migrations.AlterField(
            model_name='flight_instance',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='air_rsv.Airport'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
