# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 16:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('air_rsv', '0008_auto_20180318_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_instance',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intermediatestop',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offeredby',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validoffers',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight_instance',
            name='date_of_departure',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid date', regex='^\\s*(3[01]|[12][0-9]|0?[1-9])\\.(1[012]|0?[1-9])\\.((?:19|20)\\d{2})\\s*$')]),
        ),
        migrations.AlterField(
            model_name='flight_instance',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_rsv.Airport'),
        ),
        migrations.AlterField(
            model_name='intermediatestop',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_rsv.Flight'),
        ),
        migrations.AlterField(
            model_name='intermediatestop',
            name='stop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_rsv.Airport'),
        ),
        migrations.AlterField(
            model_name='offeredby',
            name='airline_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_rsv.Airline'),
        ),
        migrations.AlterField(
            model_name='offeredby',
            name='offer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_rsv.Offers'),
        ),
        migrations.AlterField(
            model_name='validoffers',
            name='offer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_rsv.Offers'),
        ),
        migrations.AlterField(
            model_name='validoffers',
            name='passenger_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_rsv.Passenger'),
        ),
    ]
